"""Keeps locale/translations.csv in step with the game (issue #28).

    python tools/build_translations.py

The CSV is the source of truth and is edited by hand (and by the artifact page's export).
This does exactly two mechanical things to it and nothing else:

1. **The find titles follow `assets/pieces.json`.** A `DECOR_*` row per titled decoration
   piece: added when a find is added, its `en` updated when a title is renamed. A row whose
   piece is gone is **reported, not deleted** — its translations are somebody's work, and a
   renamed slug looks exactly like a deleted one from here.
2. **The CJK fonts are cut down to the characters the table uses.** The full faces live in
   `art_source/fonts/` (22 MB, every glyph in their scripts); `assets/fonts/` gets each one
   subset to every character of its locale's column plus `CJK_ALWAYS` (2026-10-03, the
   pre-release size pass). Bungee draws all Latin first (`Style.FALLBACKS`), so only what
   Bungee lacks is ever asked of these. **Re-run after any CSV edit**, or a new character
   draws as tofu; `tools/probe_text_fit.gd` reports a glyph a face does not carry. Needs
   fontTools (`pip install --user fonttools`). Reimport afterwards.

3. **`scripts/text.gd` is written from the keys.** One static getter a key, each asking
   `TranslationServer` in the language in play, so a call site reads `Text.MENU_QUIT` and
   is never out of step with the table. Generated: do not edit it by hand.

Every other cell is left exactly as it was found.
"""
import csv
import io
import json
import re
import sys

CSV_PATH = "locale/translations.csv"
PIECES = "assets/pieces.json"
FIND_NOTE = "A piece of furniture the player finds."
FIND_BUDGET = ("13", "11", "180")

TEXT_PATH = "scripts/text.gd"


def write_text(keys) -> None:
    lines = [
        "## Every word the game shows, one getter a key of `locale/translations.csv`.",
        "## GENERATED by `tools/build_translations.py`: do not edit by hand.",
        "##",
        "## Each getter asks `TranslationServer` in the language in play, so a board that draws",
        "## `Text.KEY` in `_draw` follows a language change on its next redraw.",
        "class_name Text",
        "",
        "",
        "## One key by its name, for keys picked at runtime (a find's title).",
        "static func of(key: String) -> String:",
        "	return TranslationServer.translate(StringName(key))",
        "",
    ]
    for key in keys:
        lines += [
            "",
            "static var %s: String:" % key,
            "	get: return TranslationServer.translate(&\"%s\")" % key,
        ]
    open(TEXT_PATH, "w", encoding="utf-8", newline="").write(chr(10).join(lines) + chr(10))


FONT_SOURCE = "art_source/fonts"
FONT_OUT = "assets/fonts"
## Locale column -> the face Style.FALLBACKS draws it in when Bungee cannot.
CJK_FACES = {
    "ja": "MPLUSRounded1c-Regular.ttf",
    "zh_CN": "NotoSansSC-Variable.ttf",
    "ko": "NotoSansKR-Variable.ttf",
}
## Kept in every subset whatever the table says: CJK and full-width punctuation, the
## ideographic space, full-width digits and letters, so a later string reaching for one of
## them does not draw tofu before this is re-run.
CJK_ALWAYS = (
    "".join(chr(c) for c in range(0x3000, 0x3040))
    + "".join(chr(c) for c in range(0xFF01, 0xFF5F))
)
## Every hiragana and katakana, for the Japanese face only.
KANA = "".join(chr(c) for c in range(0x3040, 0x3100))


def subset_fonts(body, col) -> None:
    import os
    from fontTools import subset

    # Text written straight into the scripts, not the table: the flag board names each
    # language in itself (Prefs.LANGUAGES), drawn in that language's face. And the sample
    # words tools/shot_fonts.tscn photographs, so the probe never shows tofu the game cannot.
    script_cjk = set()
    sources = [os.path.join("scripts", n) for n in os.listdir("scripts") if n.endswith(".gd")]
    sources.append(os.path.join("tools", "font_samples.gd"))
    for source in sources:
        if os.path.exists(source):
            text = open(source, encoding="utf-8").read()
            script_cjk.update(ch for ch in text if ord(ch) >= 0x2E80)
    for column, face in CJK_FACES.items():
        src = os.path.join(FONT_SOURCE, face)
        if not os.path.exists(src):
            print("  no %s: fonts left as they are" % src)
            continue
        used = set(CJK_ALWAYS) | script_cjk | (set(KANA) if column == "ja" else set())
        for row in body:
            used.update(row[col[column]])
        used = {ch for ch in used if ord(ch) > 0x7F}
        options = subset.Options()
        options.layout_features = ["*"]
        options.name_IDs = ["*"]
        options.notdef_outline = True
        font = subset.load_font(src, options)
        subsetter = subset.Subsetter(options)
        subsetter.populate(unicodes=[ord(ch) for ch in used])
        subsetter.subset(font)
        out = os.path.join(FONT_OUT, face)
        subset.save_font(font, out, options)
        print("  %s: %d characters, %.0f KB" % (face, len(used), os.path.getsize(out) / 1024))


def main() -> int:
    rows = list(csv.reader(open(CSV_PATH, encoding="utf-8")))
    head = rows[0]
    if "qps" in head:  # the pseudo-locale was a debug aid, dropped 2026-10-03
        drop = head.index("qps")
        rows = [r[:drop] + r[drop + 1:] for r in rows]
        head = rows[0]
    col = {name: i for i, name in enumerate(head)}
    body = [r + [""] * (len(head) - len(r)) for r in rows[1:]]
    by_key = {r[col["keys"]]: r for r in body}

    pieces = json.load(open(PIECES, encoding="utf-8"))["pieces"]
    titles = {
        "DECOR_" + p["name"][6:].upper(): p["title"]
        for p in pieces if "title" in p and p["name"].startswith("decor_")
    }
    added, renamed = [], []
    for key, title in titles.items():
        row = by_key.get(key)
        if row is None:
            row = [""] * len(head)
            row[col["keys"]] = key
            row[col["_where"]] = "pieces.json"
            row[col["_size"]], row[col["_least"]], row[col["_width"]] = FIND_BUDGET
            row[col["_note"]] = FIND_NOTE
            row[col["en"]] = title
            body.append(row)
            by_key[key] = row
            added.append(key)
        elif row[col["en"]] != title:
            renamed.append("%s: %r -> %r" % (key, row[col["en"]], title))
            row[col["en"]] = title
    orphans = [k for k in by_key if k.startswith("DECOR_") and k not in titles]

    out = io.StringIO()
    writer = csv.writer(out, lineterminator="\n")
    writer.writerow(head)
    writer.writerows(body)
    open(CSV_PATH, "w", encoding="utf-8", newline="").write(out.getvalue())

    write_text([r[col["keys"]] for r in body])
    subset_fonts(body, col)

    print("%d rows, %d find titles" % (len(body), len(titles)))
    for key in added:
        print("  added   ", key)
    for line in renamed:
        print("  renamed ", line)
    for key in orphans:
        print("  ORPHAN  ", key, "- no piece in pieces.json has this title any more")
    return 0


if __name__ == "__main__":
    sys.exit(main())
