"""Merge Richard's Portuguese rewrite (2026-09-29) into locale/translations.csv.

His pt_BR is the source; en and the six other languages are retranslated from it.
Reads tools/ptdb/pt/*.json (the artifact's db export). One-off; run from the project root.
Columns per row: en, es, de, fr, ja, zh_CN, ko, then back-translations es, de, fr, ja, zh_CN, ko.
"""
import csv, glob, json, os

T = {
"BIND_GROUP_SHED": ["In the house", "En la casa", "Im Haus", "Dans la maison", "家の中", "屋内", "집 안",
    "In the house", "In the house", "In the house", "Inside the house", "Indoors", "Inside the house"],
"BLURB_BOAT_SPEED": ["How fast the boats travel between the island and the piers.",
    "La velocidad de los barcos entre la isla y los muelles.",
    "Wie schnell die Boote zwischen Insel und Stegen fahren.",
    "La vitesse des bateaux entre l'île et les pontons.",
    "島と桟橋のあいだを進むボートの速さ。", "船只在小岛和码头之间航行的速度。", "섬과 부두 사이를 오가는 배의 속도.",
    "The speed of the boats between the island and the piers.", "How fast the boats travel between island and piers.",
    "The speed of the boats between the island and the piers.", "The speed of boats moving between island and pier.",
    "The speed at which boats sail between the island and the docks.", "The speed of boats going between island and pier."],
"BLURB_BOAT_VOLLEY": ["How quickly the boats load up and throw it into the piers' boxes.",
    "La rapidez con que los barcos cargan y lo echan en las cajas de los muelles.",
    "Wie schnell die Boote laden und alles in die Kisten der Stege werfen.",
    "La rapidité avec laquelle les bateaux chargent et jettent tout dans les caisses des pontons.",
    "ボートが荷を積み、桟橋の箱に投げ入れる速さ。", "船只装货并把货物扔进码头箱子的速度。", "배가 짐을 싣고 부두 상자에 던져 넣는 속도.",
    "How quickly the boats load and throw it into the piers' boxes.", "How fast the boats load and throw everything into the piers' boxes.",
    "How quickly the boats load and throw everything into the piers' crates.", "How fast boats load cargo and throw it into the pier boxes.",
    "How fast boats load and throw cargo into the dock boxes.", "How fast boats load cargo and throw it into pier boxes."],
"BLURB_CARGO": ["How many pieces the boats carry a trip.", "Cuántas piezas llevan los barcos por viaje.",
    "Wie viele Teile die Boote pro Fahrt tragen.", "Combien de pièces les bateaux portent par trajet.",
    "ボートが1回に運べる数。", "船只每趟运载的数量。", "배가 한 번에 나르는 개수.",
    "How many pieces the boats carry per trip.", "How many pieces the boats carry per trip.", "How many pieces the boats carry per trip.",
    "The number boats can carry at once.", "How many items boats carry per trip.", "How many a boat carries at once."],
"BLURB_DOG_COUNT": ["One more dog for the pack.", "Un perro más para la manada.", "Ein Hund mehr fürs Rudel.",
    "Un chien de plus dans la meute.", "群れにもう1匹の犬。", "狗群再添一只狗。", "무리에 개 한 마리 추가.",
    "One more dog for the pack.", "One more dog for the pack.", "One more dog in the pack.",
    "One more dog in the pack.", "One more dog joins the pack.", "Add one dog to the pack."],
"BLURB_DOG_FETCH": ["How many pieces the dogs bring back a trip.", "Cuántas piezas traen los perros por viaje.",
    "Wie viele Teile die Hunde pro Gang bringen.", "Combien de pièces les chiens rapportent par trajet.",
    "犬が1回に持ち帰る数。", "狗每趟叼回的数量。", "개가 한 번에 물어 오는 개수.",
    "How many pieces the dogs bring per trip.", "How many pieces the dogs bring per trip.", "How many pieces the dogs bring back per trip.",
    "The number a dog brings back at once.", "How many items the dogs fetch per trip.", "How many a dog fetches at once."],
"BLURB_DOG_STRENGTH": ["The weight tier of the pieces the dogs can carry.", "El nivel de peso de las piezas que cargan los perros.",
    "Die Gewichtsstufe der Teile, die Hunde tragen können.", "Le niveau de poids des pièces que les chiens portent.",
    "犬が運べるものの重さランク。", "狗能搬运的物品重量等级。", "개가 옮길 수 있는 물건의 무게 등급.",
    "The weight level of the pieces the dogs carry.", "The weight tier of the pieces dogs can carry.", "The weight level of the pieces the dogs carry.",
    "The weight rank of things a dog can carry.", "The weight tier of items the dogs can carry.", "The weight tier of items a dog can carry."],
"BLURB_DOG_WAIT": ["How long a dog rests between trips, at most.", "Cuánto descansa un perro entre viajes, como máximo.",
    "Wie lange ein Hund zwischen den Gängen höchstens ruht.", "Combien de temps un chien se repose entre deux trajets, au plus.",
    "犬が次に出るまで休む最長の時間。", "狗在两趟之间最多休息多久。", "개가 다음 심부름 전까지 쉬는 최대 시간.",
    "How long a dog rests between trips, at most.", "How long a dog rests between trips at most.", "How long a dog rests between trips, at most.",
    "The longest time a dog rests before going out again.", "The longest a dog rests between trips.", "The longest a dog rests before its next errand."],
"BLURB_FLEET": ["Adds another boat on the water.", "Añade otro barco al agua.", "Ein weiteres Boot aufs Wasser.",
    "Ajoute un autre bateau sur l'eau.", "水上にボートを1隻追加。", "水上再添一艘船。", "물 위에 배를 한 척 추가.",
    "Adds another boat to the water.", "One more boat on the water.", "Adds another boat on the water.",
    "Adds one boat on the water.", "Add one more boat on the water.", "Add one boat on the water."],
"BLURB_LUCKY_HAUL": ["Odds that a cast catches heavier tiers and more pieces.",
    "Probabilidad de que un lanzamiento atrape niveles más pesados y más piezas.",
    "Chance, dass ein Wurf schwerere Stufen und mehr Teile fängt.",
    "Chance qu'un lancer attrape des niveaux plus lourds et plus de pièces.",
    "投げたとき、重いランクを多めに取れる確率。", "一次抛网捞到更重等级和更多物品的几率。", "던졌을 때 더 무거운 등급을 더 많이 잡을 확률.",
    "Chance that a cast catches heavier tiers and more pieces.", "Chance that a throw catches heavier tiers and more pieces.",
    "Chance that a cast catches heavier levels and more pieces.", "Chance a throw catches more of a heavier rank.",
    "Chance that one cast nets heavier tiers and more items.", "Chance of catching more of a heavier tier on a throw."],
"BLURB_NET_RANGE": ["How far the angler can throw the net.", "Hasta dónde puede lanzar la red el pescador.",
    "Wie weit der Angler das Netz werfen kann.", "Jusqu'où le pêcheur peut lancer le filet.",
    "網を投げられる距離。", "渔夫能把网抛多远。", "그물을 던질 수 있는 거리.",
    "How far the fisherman can throw the net.", "How far the angler can throw the net.", "How far the fisherman can throw the net.",
    "The distance you can throw the net.", "How far the fisherman can cast the net.", "The distance the net can be thrown."],
"BLURB_NET_STRENGTH": ["Which weight tiers the net can catch.", "Qué niveles de peso puede atrapar la red.",
    "Welche Gewichtsstufen das Netz fangen kann.", "Quels niveaux de poids le filet peut attraper.",
    "網が取れる重さランク。", "网能捞起哪些重量等级。", "그물이 잡을 수 있는 무게 등급.",
    "Which weight levels the net can catch.", "Which weight tiers the net can catch.", "Which weight levels the net can catch.",
    "The weight ranks the net can take.", "Which weight tiers the net can catch.", "The weight tiers the net can catch."],
"BLURB_NET_WIDTH": ["The size of the net, and how much each cast covers.", "El tamaño de la red y cuánto cubre cada lanzamiento.",
    "Die Größe des Netzes und wie viel jeder Wurf abdeckt.", "La taille du filet et ce que couvre chaque lancer.",
    "網の大きさと、1回で届く広さ。", "网的大小，以及每次抛网覆盖的范围。", "그물의 크기와 한 번에 덮는 넓이.",
    "The size of the net and how much each throw covers.", "The size of the net and how much each throw covers.",
    "The size of the net and what each cast covers.", "The size of the net and the area one throw reaches.",
    "The size of the net and the area each cast covers.", "The size of the net and the area it covers at once."],
"BLURB_RECYCLE_BONUS": ["Adds a bonus to one pier at a time, every 30s.", "Añade un bono a un muelle a la vez, cada 30 s.",
    "Ein Bonus auf je einen Steg, alle 30 s.", "Ajoute un bonus à un ponton à la fois, toutes les 30 s.",
    "30秒ごとに、桟橋1つにボーナス。", "每30秒为一个码头加成。", "30초마다 부두 하나에 보너스.",
    "Adds a bonus to one pier at a time, every 30 s.", "A bonus on one pier at a time, every 30 s.",
    "Adds a bonus to one pier at a time, every 30 s.", "A bonus on one pier every 30 seconds.",
    "Gives one dock a bonus every 30 seconds.", "A bonus on one pier every 30 seconds."],
"CONFIRM_BINDS_YES": ["Use default", "Por defecto", "Standard nutzen", "Par défaut", "初期設定に戻す", "恢复默认", "기본값 사용",
    "Use default", "Use default", "By default", "Return to initial settings", "Restore default", "Use default"],
"CONFIRM_NEW_NO": ["Cancel", "Cancelar", "Abbrechen", "Annuler", "キャンセル", "取消", "취소",
    "Cancel", "Cancel", "Cancel", "Cancel", "Cancel", "Cancel"],
"CONFIRM_NEW_TITLE": ["Start over?", "¿Empezar de nuevo?", "Neu anfangen?", "Recommencer ?", "最初からやり直す？", "要重新开始吗？", "처음부터 다시 할까요?",
    "Start over?", "Start again?", "Start over?", "Start over from the beginning?", "Do you want to start over?", "Start over from the beginning?"],
"CONFIRM_NEW_WORDS": ["Your progress will be erased.", "Tu progreso actual se borrará.", "Dein aktueller Fortschritt wird gelöscht.",
    "Ta progression actuelle sera effacée.", "今の進行は消えます。", "当前进度将被清除。", "지금까지의 진행이 지워져요.",
    "Your current progress will be erased.", "Your current progress will be deleted.", "Your current progress will be erased.",
    "Current progress will disappear.", "Current progress will be cleared.", "Your progress so far will be erased."],
"CREDITS_HEAD_ART": ["Art", "Arte", "Grafik", "Graphismes", "アート", "美术", "아트",
    "Art", "Graphics", "Graphics", "Art", "Art", "Art"],
"CREDITS_HEAD_DESIGN": ["Design and production", "Diseño y producción", "Design und Produktion", "Conception et production",
    "デザイン・制作", "设计与制作", "디자인 및 제작",
    "Design and production", "Design and production", "Design and production", "Design and production", "Design and production", "Design and production"],
"DECOR_BIG_RUG": ["Rug", "Alfombra", "Teppich", "Tapis", "じゅうたん", "地毯", "러그", "Rug", "Rug", "Rug", "Carpet", "Rug", "Rug"],
"DECOR_BIG_TABLE": ["Table", "Mesa", "Tisch", "Table", "テーブル", "桌子", "테이블", "Table", "Table", "Table", "Table", "Table", "Table"],
"DECOR_BOOKCASE_TALL": ["Bookcase", "Estantería", "Bücherregal", "Bibliothèque", "本棚", "书架", "책장",
    "Bookcase", "Bookcase", "Bookcase", "Bookshelf", "Bookshelf", "Bookcase"],
"DECOR_CENTER_TABLE": ["Coffee table", "Mesa de centro", "Couchtisch", "Table basse", "ローテーブル", "茶几", "커피 테이블",
    "Coffee table", "Coffee table", "Coffee table", "Low table", "Coffee table", "Coffee table"],
"DECOR_CHEW_TOY": ["Pet toy", "Juguete de mascota", "Haustierspielzeug", "Jouet pour animal", "ペットのおもちゃ", "宠物玩具", "반려동물 장난감",
    "Pet toy", "Pet toy", "Pet toy", "Pet's toy", "Pet toy", "Pet toy"],
"DECOR_DINING_CHAIR": ["Chair", "Silla", "Stuhl", "Chaise", "いす", "椅子", "의자", "Chair", "Chair", "Chair", "Chair", "Chair", "Chair"],
"DECOR_FLOWER_POT": ["Flower pot", "Maceta", "Blumentopf", "Pot de fleur", "植木鉢", "花盆", "화분",
    "Flowerpot", "Flower pot", "Flower pot", "Plant pot", "Flower pot", "Flower pot"],
"DECOR_MIRROR": ["Mirror", "Espejo", "Spiegel", "Miroir", "鏡", "镜子", "거울", "Mirror", "Mirror", "Mirror", "Mirror", "Mirror", "Mirror"],
"DECOR_NIGHTSTAND": ["Small table", "Mesita", "Beistelltisch", "Petite table", "小さなテーブル", "小桌", "작은 테이블",
    "Small table", "Side table", "Small table", "Small table", "Small table", "Small table"],
"DECOR_OLD_CLOCK": ["Clock", "Reloj", "Uhr", "Horloge", "時計", "时钟", "시계", "Clock", "Clock", "Clock", "Clock", "Clock", "Clock"],
"DECOR_OLD_RUG": ["Rug", "Alfombra", "Teppich", "Tapis", "じゅうたん", "地毯", "러그", "Rug", "Rug", "Rug", "Carpet", "Rug", "Rug"],
"DECOR_PAINTING_B": ["Painting", "Cuadro", "Bild", "Tableau", "絵", "画", "그림", "Painting", "Picture", "Painting", "Picture", "Painting", "Painting"],
"DECOR_PET_BED": ["Pet bed", "Cama de mascota", "Haustierbett", "Lit pour animal", "ペットベッド", "宠物床", "반려동물 침대",
    "Pet bed", "Pet bed", "Pet bed", "Pet bed", "Pet bed", "Pet bed"],
"DECOR_STANDING_LAMP": ["Lamp", "Lámpara", "Lampe", "Lampe", "ランプ", "灯", "램프", "Lamp", "Lamp", "Lamp", "Lamp", "Lamp", "Lamp"],
"DECOR_TINY_BOOKCASE": ["Bookcase", "Estantería", "Bücherregal", "Bibliothèque", "本棚", "书架", "책장",
    "Bookcase", "Bookcase", "Bookcase", "Bookshelf", "Bookshelf", "Bookcase"],
"END_LINE_1": ["The lake is clean, and now you can live in peace.", "El lago está limpio y ahora puedes vivir en paz.",
    "Der See ist sauber, und jetzt kannst du in Frieden leben.", "Le lac est propre, et tu peux enfin vivre en paix.",
    "湖はきれいになった。これで穏やかに暮らせます。", "湖变干净了，现在你可以安宁地生活了。", "호수가 깨끗해졌어요. 이제 평화롭게 살 수 있어요.",
    "The lake is clean and now you can live in peace.", "The lake is clean, and now you can live in peace.",
    "The lake is clean, and you can finally live in peace.", "The lake became clean. Now you can live calmly.",
    "The lake is clean; now you can live in peace.", "The lake is clean. Now you can live in peace."],
"HUD_AVAILABLE": ["%d ready", "%d listas", "%d bereit", "%d prêtes", "%d 件", "%d 项可用", "%d개 가능",
    "%d ready", "%d ready", "%d ready", "%d items", "%d available", "%d possible"],
"HUD_WAITING": ["Waiting", "Esperando", "Wartet", "En attente", "待ち", "等待中", "대기",
    "Waiting", "Waiting", "Waiting", "Waiting", "Waiting", "Waiting"],
"LETTER_DECOR_CAP1": ["Catch objects", "Atrapa objetos", "Fang Objekte", "Attrape des objets", "ものを取る", "捞起物品", "물건 잡기",
    "Catch objects", "Catch objects", "Catch objects", "Take things", "Catch items", "Catch things"],
"LETTER_DECOR_LINE": ["Some catches are decorations for your house.", "Algunas capturas son decoración para tu casa.",
    "Manche Fänge sind Deko für dein Haus.", "Certaines prises sont des décorations pour ta maison.",
    "取ったものの中には、家の飾りになるものもあります。", "有些捞到的东西可以用来装饰你的房子。", "잡은 것 중 일부는 집을 꾸미는 장식이에요.",
    "Some catches are decoration for your house.", "Some catches are decorations for your house.", "Some catches are decorations for your house.",
    "Some things you catch become decorations for the house.", "Some things you catch can decorate your house.", "Some catches are decorations for your house."],
"LETTER_GAME_NAME": ["Dirty Little Lake."] * 7 + ["Dirty Little Lake. (untranslated)"] * 6,
"LETTER_GREETING_LEAD": ["You are the new owner of ", "Eres el nuevo propietario de ", "Du bist der neue Besitzer von ",
    "Tu es le nouveau propriétaire de ", "新しい持ち主はあなた：", "你是这片湖的新主人：", "새 주인은 바로 당신: ",
    "You are the new owner of ", "You are the new owner of ", "You are the new owner of ",
    "The new owner is you: ", "You are the new owner of this lake: ", "The new owner is you: "],
"LETTER_START": ["Start cleaning", "Empezar a limpiar", "Los geht's", "Au nettoyage", "そうじを始める", "开始清理", "청소 시작",
    "Start cleaning", "Let's go", "Time to clean", "Start cleaning", "Start cleaning", "Start cleaning"],
"LETTER_UPGRADES_BOATS": ["Boats *sell objects for money* at the recycling piers.",
    "Los barcos *venden objetos por dinero* en los muelles de reciclaje.",
    "Boote *verkaufen Objekte für Geld* an den Recyclingstegen.",
    "Les bateaux *vendent les objets contre de l'argent* aux pontons de recyclage.",
    "ボートはリサイクル桟橋で*ものを売ってお金にします*。", "船会在回收码头*卖掉物品换钱*。", "배는 재활용 부두에서 *물건을 팔아 돈을 벌어요*.",
    "Boats *sell objects for money* at the recycling piers.", "Boats *sell objects for money* at the recycling piers.",
    "Boats *sell objects for money* at the recycling piers.", "Boats *sell things for money* at the recycling piers.",
    "Boats *sell items for money* at the recycling docks.", "Boats *sell things to make money* at the recycling piers."],
"LETTER_UPGRADES_DOGS": ["Dogs *help clean the lake*.", "Los perros *ayudan a limpiar el lago*.", "Hunde *helfen, den See zu säubern*.",
    "Les chiens *aident à nettoyer le lac*.", "犬は*湖のそうじを手伝います*。", "狗会*帮忙清理湖泊*。", "개는 *호수 청소를 도와요*.",
    "Dogs *help clean the lake*.", "Dogs *help clean the lake*.", "Dogs *help clean the lake*.",
    "Dogs *help clean the lake*.", "Dogs *help clean the lake*.", "Dogs *help clean the lake*."],
"LETTER_UPGRADES_NET": ["Upgrade your net to *catch more objects, with more precision and range.*",
    "Mejora tu red para *atrapar más objetos, con más precisión y alcance.*",
    "Verbessere dein Netz, um *mehr Objekte zu fangen, präziser und weiter.*",
    "Améliore ton filet pour *attraper plus d'objets, avec plus de précision et de portée.*",
    "網を強化して*もっと多く、正確に、遠くまで取ろう。*", "升级渔网，*捞到更多物品，更精准，更远。*", "그물을 업그레이드해서 *더 많이, 더 정확하게, 더 멀리 잡아요.*",
    "Improve your net to *catch more objects, with more precision and reach.*", "Improve your net to *catch more objects, more precisely and further.*",
    "Improve your net to *catch more objects, with more precision and range.*", "Upgrade the net to *take more, more accurately, further.*",
    "Upgrade the net to *catch more items, more precisely, further.*", "Upgrade the net to *catch more, more accurately, further.*"],
"LETTER_WEIGHT_TEXT": ["Objects have *5 weight tiers*.\nUpgrading Strength *lets you catch objects of each tier*.",
    "Los objetos tienen *5 niveles de peso*.\nMejorar la Fuerza *te deja atrapar objetos de cada nivel*.",
    "Objekte haben *5 Gewichtsstufen*.\nMehr Stärke *lässt dich Objekte jeder Stufe fangen*.",
    "Les objets ont *5 niveaux de poids*.\nAméliorer la Force *permet d'attraper les objets de chaque niveau*.",
    "ものには*5つの重さランク*があります。\nパワーを強化すると*各ランクのものが取れるようになります*。",
    "物品分为*5个重量等级*。\n升级力量*就能捞起每个等级的物品*。",
    "물건에는 *5개의 무게 등급*이 있어요.\n힘을 업그레이드하면 *각 등급의 물건을 잡을 수 있어요*.",
    "Objects have *5 weight levels*.\nImproving Strength *lets you catch objects of each level*.",
    "Objects have *5 weight tiers*.\nMore Strength *lets you catch objects of every tier*.",
    "Objects have *5 weight levels*.\nImproving Strength *lets you catch the objects of each level*.",
    "Things have *5 weight ranks*.\nUpgrading Power *lets you take things of each rank*.",
    "Items come in *5 weight tiers*.\nUpgrading strength *lets you catch items of every tier*.",
    "Things have *5 weight tiers*.\nUpgrading strength *lets you catch things of each tier*."],
"LETTER_WELCOME_TEXT": ["It has been abandoned and neglected for too long.\nYour goal is to *catch objects with your net, recycle and bring life back to the lake.*\nThe following instructions will *teach you how it works.*",
    "Ha estado abandonado y olvidado demasiado tiempo.\nTu objetivo es *atrapar objetos con la red, reciclar y devolverle la vida al lago.*\nLas siguientes instrucciones te *enseñarán cómo funciona.*",
    "Er war zu lange verlassen und vergessen.\nDein Ziel: *Objekte mit dem Netz fangen, recyceln und den See wieder zum Leben erwecken.*\nDie folgenden Hinweise *zeigen dir, wie es geht.*",
    "Il a été abandonné et négligé trop longtemps.\nTon but : *attraper des objets avec ton filet, recycler et rendre la vie au lac.*\nLes instructions suivantes vont *t'apprendre comment ça marche.*",
    "長いあいだ、放っておかれていました。\n目標は*網でものを取り、リサイクルして、湖に命を取り戻すこと。*\nこの先の説明で*やり方がわかります。*",
    "它被遗弃、荒废了太久。\n你的目标是*用网捞起物品，回收利用，让湖泊重获生机。*\n接下来的说明会*教你怎么玩。*",
    "너무 오랫동안 버려지고 방치되었어요.\n목표는 *그물로 물건을 잡고, 재활용해서 호수에 생명을 되찾아 주는 것.*\n다음 안내가 *방법을 알려 줄 거예요.*",
    "It has been abandoned and forgotten for too long.\nYour goal is to *catch objects with the net, recycle and bring life back to the lake.*\nThe following instructions will *teach you how it works.*",
    "It was abandoned and forgotten for too long.\nYour goal: *catch objects with the net, recycle and bring the lake back to life.*\nThe following notes *show you how.*",
    "It was abandoned and neglected too long.\nYour goal: *catch objects with your net, recycle and bring life back to the lake.*\nThe following instructions will *teach you how it works.*",
    "It was left alone for a long time.\nThe goal is *to take things with the net, recycle, and restore life to the lake.*\nThe explanations ahead *show you how.*",
    "It was abandoned and neglected for too long.\nYour goal is to *catch items with the net, recycle, and bring the lake back to life.*\nThe following instructions *teach you how to play.*",
    "It was abandoned and neglected for too long.\nThe goal is *catching things with the net, recycling, and giving life back to the lake.*\nThe next guide *will show you how.*"],
"LETTER_WELCOME_TITLE": ["Welcome", "Bienvenida", "Willkommen", "Bienvenue", "ようこそ", "欢迎", "환영해요",
    "Welcome", "Welcome", "Welcome", "Welcome", "Welcome", "Welcome"],
"MENU_QUIT": ["Save and quit", "Guardar y salir", "Speichern & Ende", "Sauver et quitter", "セーブして終了", "保存并退出", "저장 후 종료",
    "Save and quit", "Save and quit", "Save and quit", "Save and quit", "Save and quit", "Save and quit"],
"RECORD_SHED": ["House", "Casa", "Haus", "Maison", "家", "屋内", "집", "House", "House", "House", "House", "Indoors", "House"],
"RECORD_SYNC": ["Sync", "Sync", "Sync", "Sync", "同期", "同步", "동기화", "Sync", "Sync", "Sync", "Sync", "Sync", "Sync"],
"SHELF_EMPTY": ["No decorations.", "Sin decoración.", "Keine Deko.", "Aucune déco.", "飾りなし。", "暂无装饰。", "장식 없음.",
    "No decoration.", "No decorations.", "No decoration.", "No decorations.", "No decorations yet.", "No decorations."],
"SHOP_GROUP_AT_YARDS": ["At the piers", "En los muelles", "An den Stegen", "Aux pontons", "桟橋で", "码头", "부두에서",
    "At the piers", "At the piers", "At the piers", "At the piers", "Docks", "At the piers"],
"SHOP_GROUP_FLEET": ["Number of boats", "Número de barcos", "Anzahl Boote", "Nombre de bateaux", "ボートの数", "船只数量", "배 수",
    "Number of boats", "Number of boats", "Number of boats", "Number of boats", "Number of boats", "Number of boats"],
"SHOP_GROUP_RUN": ["Progress", "Progreso", "Fortschritt", "Progression", "進み", "进度", "진행",
    "Progress", "Progress", "Progress", "Progress", "Progress", "Progress"],
"SHOP_GROUP_TRIP": ["Helping", "Ayuda", "Helfen", "Aide", "手伝い", "帮忙", "도움",
    "Help", "Helping", "Help", "Helping", "Helping", "Help"],
"SHOP_LEGEND": ["Boats visit their piers to recycle and sell each material. The prices above are the average paid per piece.",
    "Los barcos visitan sus muelles para reciclar y vender cada material. Los precios de arriba son el promedio por pieza.",
    "Boote fahren zu ihren Stegen, um jedes Material zu recyceln und zu verkaufen. Die Preise oben sind der Schnitt pro Teil.",
    "Les bateaux vont à leurs pontons recycler et vendre chaque matériau. Les prix ci-dessus sont la moyenne par pièce.",
    "ボートは各桟橋で素材をリサイクルして売ります。上の値段は1つあたりの平均です。",
    "船只前往各自的码头回收并出售材料。上方价格为每件的平均售价。",
    "배는 각 부두에서 재료를 재활용해 팔아요. 위 가격은 개당 평균이에요.",
    "Boats visit their piers to recycle and sell each material. The prices above are the average per piece.",
    "Boats go to their piers to recycle and sell each material. The prices above are the average per piece.",
    "Boats go to their piers to recycle and sell each material. The prices above are the average per piece.",
    "Boats recycle and sell materials at each pier. The prices above are the average per item.",
    "Boats go to their docks to recycle and sell materials. Prices above are average per item.",
    "Boats recycle and sell materials at each pier. The prices above are the per-item average."],
"STEPS_NOTE": ["Objects go to the recycle box, and boats take them to the piers for money",
    "Los objetos van a la caja de reciclaje y los barcos los llevan a los muelles por dinero",
    "Objekte kommen in die Recyclingkiste, und Boote bringen sie für Geld zu den Stegen",
    "Les objets vont dans la caisse de recyclage, et les bateaux les portent aux pontons contre de l'argent",
    "ものはリサイクル箱へ。ボートが桟橋に運んでお金にします",
    "物品会进入回收箱，船只把它们运到码头换钱",
    "물건은 재활용 상자로 가고, 배가 부두로 옮겨 돈으로 바꿔요",
    "Objects go to the recycling box and boats take them to the piers for money",
    "Objects go into the recycling crate, and boats take them to the piers for money",
    "Objects go into the recycling crate, and boats carry them to the piers for money",
    "Things go to the recycle box. Boats carry them to the piers for money",
    "Items go into the recycling box; boats carry them to the docks for money",
    "Things go to the recycle box, and boats take them to the piers for money"],
"TOUR_DECOR_HINT": ["You found a decoration! Open Decorate to see it.", "¡Encontraste una decoración! Abre Decorar para verla.",
    "Du hast eine Deko gefunden! Öffne Dekorieren, um sie zu sehen.", "Tu as trouvé une décoration ! Ouvre Décorer pour la voir.",
    "飾りを見つけた！「飾る」を開いて見てみよう。", "你找到了一件装饰！打开“装饰”查看。", "장식을 찾았어요! 꾸미기를 열어 확인하세요.",
    "You found a decoration! Open Decorate to see it.", "You found a decoration! Open Decorate to see it.", "You found a decoration! Open Decorate to see it.",
    "Found a decoration! Open Decorate and take a look.", "You found a decoration! Open Decorate to view it.", "You found a decoration! Open Decorate to check it."],
"TOUR_DECOR_ROOM": ["You can interact with some objects by pressing %s. It shows when available.",
    "Puedes interactuar con algunos objetos pulsando %s. Aparece cuando se puede.",
    "Mit manchen Objekten kannst du mit %s interagieren. Es wird angezeigt, wenn es geht.",
    "Tu peux interagir avec certains objets en appuyant sur %s. C'est indiqué quand c'est possible.",
    "%s で使えるものがあります。使えるときは表示されます。",
    "按 %s 可以与某些物品互动。可用时会有提示。",
    "%s 를 눌러 일부 물건과 상호작용할 수 있어요. 가능할 때 표시돼요.",
    "You can interact with some objects by pressing %s. It shows when you can.",
    "You can interact with some objects with %s. It shows when possible.",
    "You can interact with some objects by pressing %s. It is shown when possible.",
    "Some things can be used with %s. It shows when usable.",
    "Press %s to interact with some items. A prompt shows when available.",
    "Press %s to interact with some things. It shows when possible."],
"TOUR_DECOR_STAND": ["Point and click to wash the dirt off with water. It goes to the decoration inventory when done.",
    "Apunta y haz clic para lavar la suciedad con agua. Al terminar, va al inventario de decoración.",
    "Zielen und klicken, um den Dreck abzuwaschen. Danach landet es im Deko-Inventar.",
    "Vise et clique pour laver la saleté à l'eau. Une fois fini, ça va dans l'inventaire de déco.",
    "狙ってクリックし、水で汚れを洗い流そう。終わると飾りの持ち物に入ります。",
    "瞄准并点击，用水冲掉污垢。洗完后会放入装饰库存。",
    "조준하고 클릭해서 물로 때를 씻어요. 다 되면 장식 보관함으로 가요.",
    "Point and click to wash off the dirt with water. When done, it goes to the decoration inventory.",
    "Aim and click to wash off the dirt. Then it lands in the decoration inventory.",
    "Aim and click to wash the dirt off with water. Once done, it goes into the decoration inventory.",
    "Aim and click to wash off the dirt with water. When done it goes to your decorations.",
    "Aim and click to rinse off the dirt. When done it goes into the decoration inventory.",
    "Aim and click to wash off the dirt. When done, it goes to decoration storage."],
"TOUR_DECOR_STAND_PAD": ["Aim and hold %s to wash the dirt off with water. It goes to the decoration inventory when done.",
    "Apunta y mantén %s para lavar la suciedad con agua. Al terminar, va al inventario de decoración.",
    "Zielen und %s halten, um den Dreck abzuwaschen. Danach landet es im Deko-Inventar.",
    "Vise et maintiens %s pour laver la saleté à l'eau. Une fois fini, ça va dans l'inventaire de déco.",
    "狙って %s を押し続け、水で汚れを洗い流そう。終わると飾りの持ち物に入ります。",
    "瞄准并按住 %s，用水冲掉污垢。洗完后会放入装饰库存。",
    "조준하고 %s 를 눌러 물로 때를 씻어요. 다 되면 장식 보관함으로 가요.",
    "Aim and hold %s to wash off the dirt with water. When done, it goes to the decoration inventory.",
    "Aim and hold %s to wash off the dirt. Then it lands in the decoration inventory.",
    "Aim and hold %s to wash the dirt off with water. Once done, it goes into the decoration inventory.",
    "Aim and hold %s to wash off dirt. When done it goes to your decorations.",
    "Aim and hold %s to rinse off dirt. When done it goes into the decoration inventory.",
    "Aim and hold %s to wash off dirt. When done, it goes to decoration storage."],
"TOUR_SHOP_AT_YARDS": ["You can make more money by giving recycling a bonus, and pigeons can earn more.",
    "Puedes ganar más dinero dando un bono al reciclaje, y las palomas pueden rendir más.",
    "Mit einem Recyclingbonus verdienst du mehr, und Tauben können mehr einbringen.",
    "Tu gagnes plus en donnant un bonus au recyclage, et les pigeons peuvent rapporter plus.",
    "リサイクルにボーナスをつけると稼ぎが増え、ハトももっと稼げます。",
    "给回收加成可以赚更多钱，鸽子也能带来更多收入。",
    "재활용에 보너스를 주면 더 벌고, 비둘기도 더 많이 벌 수 있어요.",
    "You can earn more money by giving recycling a bonus, and pigeons can earn more.",
    "With a recycling bonus you earn more, and pigeons can bring in more.",
    "You earn more by giving recycling a bonus, and pigeons can bring in more.",
    "Adding a bonus to recycling earns more, and pigeons can earn more too.",
    "A recycling bonus earns more money, and pigeons can bring in more too.",
    "A bonus on recycling earns more, and pigeons can earn more too."],
"TOUR_SHOP_BOATS": ["Boats are essential for making money, and upgrades raise their speed and cargo size.",
    "Los barcos son esenciales para ganar dinero, y las mejoras aumentan su velocidad y su carga.",
    "Boote sind zum Geldverdienen unverzichtbar, und Upgrades erhöhen Tempo und Ladung.",
    "Les bateaux sont essentiels pour gagner de l'argent, et les améliorations augmentent leur vitesse et leur charge.",
    "ボートはお金を稼ぐのに欠かせません。強化すると速さと積める量が上がります。",
    "船只是赚钱的关键，升级可以提高速度和载货量。",
    "배는 돈을 버는 데 꼭 필요해요. 업그레이드하면 속도와 적재량이 늘어요.",
    "Boats are essential to make money, and upgrades increase their speed and load.",
    "Boats are essential for earning money, and upgrades raise speed and load.",
    "Boats are essential to earn money, and upgrades increase their speed and load.",
    "Boats are vital for earning money. Upgrading raises their speed and how much they carry.",
    "Boats are key to making money; upgrades raise speed and cargo capacity.",
    "Boats are needed to earn money. Upgrades increase speed and capacity."],
"TOUR_SHOP_DOGS": ["Dogs help take objects to the recycle box.", "Los perros ayudan a llevar objetos a la caja de reciclaje.",
    "Hunde helfen, Objekte zur Recyclingkiste zu bringen.", "Les chiens aident à porter les objets à la caisse de recyclage.",
    "犬はものをリサイクル箱まで運ぶのを手伝います。", "狗会帮忙把物品送到回收箱。", "개는 물건을 재활용 상자로 옮기는 걸 도와요.",
    "Dogs help carry objects to the recycling box.", "Dogs help bring objects to the recycling crate.", "Dogs help carry objects to the recycling crate.",
    "Dogs help carry things to the recycle box.", "Dogs help bring items to the recycling box.", "Dogs help move things to the recycle box."],
"TOUR_SHOP_LEGEND": ["Here you can see each material's average price, and which recycling pier has a bonus.",
    "Aquí ves el precio medio de cada material y qué muelle de reciclaje tiene bono.",
    "Hier siehst du den Durchschnittspreis jedes Materials und welcher Recyclingsteg einen Bonus hat.",
    "Ici tu vois le prix moyen de chaque matériau, et quel ponton de recyclage a un bonus.",
    "ここで素材ごとの平均価格と、ボーナス中の桟橋がわかります。",
    "这里可以看到各材料的平均价格，以及哪个回收码头有加成。",
    "여기서 재료별 평균 가격과 보너스가 붙은 부두를 볼 수 있어요.",
    "Here you see the average price of each material and which recycling pier has a bonus.",
    "Here you see each material's average price and which recycling pier has a bonus.",
    "Here you see the average price of each material, and which recycling pier has a bonus.",
    "Here you can see each material's average price and which pier has a bonus.",
    "Here you can see each material's average price and which recycling dock has a bonus.",
    "Here you can see the average price per material and which pier has a bonus."],
"TOUR_SHOP_NET": ["Your net can be upgraded to catch more objects of higher tiers, and to cast and reel faster.",
    "Tu red puede mejorarse para atrapar más objetos de niveles más altos y lanzar y recoger más rápido.",
    "Dein Netz lässt sich verbessern: mehr Objekte, höhere Stufen, schneller werfen und einholen.",
    "Ton filet peut être amélioré pour attraper plus d'objets de niveaux plus élevés, et lancer et ramener plus vite.",
    "網を強化すると、重いランクのものを多く取れて、投げるのも巻くのも速くなります。",
    "渔网可以升级，捞到更多更高等级的物品，抛网收网更快。",
    "그물을 업그레이드하면 더 높은 등급의 물건을 더 많이 잡고, 더 빨리 던지고 감을 수 있어요.",
    "Your net can be improved to catch more objects of higher levels and cast and reel faster.",
    "Your net can be upgraded: more objects, higher tiers, faster casting and reeling.",
    "Your net can be improved to catch more objects of higher levels, and cast and reel in faster.",
    "Upgrading the net lets you take more of heavier ranks and throw and reel faster.",
    "The net can be upgraded to catch more higher-tier items and cast and reel faster.",
    "Upgrading the net lets you catch more higher-tier things and throw and reel faster."],
"TOUR_SHOP_ON_CAST": ["Upgrades also raise the odds of a lucky net or a double cast.",
    "Las mejoras también aumentan la probabilidad de una red de la suerte o de un lanzamiento doble.",
    "Upgrades erhöhen auch die Chance auf ein Glücksnetz oder einen Doppelwurf.",
    "Les améliorations augmentent aussi les chances d'un filet chanceux ou d'un double lancer.",
    "強化すると、ラッキーネットやダブル投げの確率も上がります。",
    "升级也会提高幸运网和双重抛网的几率。",
    "업그레이드하면 행운의 그물과 더블 던지기 확률도 올라가요.",
    "Upgrades also increase the chance of a lucky net or a double cast.",
    "Upgrades also raise the chance of a lucky net or a double throw.",
    "Upgrades also increase the chances of a lucky net or a double cast.",
    "Upgrading also raises the chance of a lucky net or a double throw.",
    "Upgrades also raise the chance of a lucky net or double cast.",
    "Upgrades also raise the chance of a lucky net and double throw."],
"TRACK_BOAT_SPEED": ["Speed", "Rapidez", "Tempo", "Vitesse", "速さ", "速度", "속도",
    "Speed", "Speed", "Speed", "Speed", "Speed", "Speed"],
"TRACK_BOAT_VOLLEY": ["Loading", "Carga", "Laden", "Charge", "荷役", "装卸", "하역",
    "Load", "Loading", "Load", "Cargo handling", "Loading and unloading", "Loading"],
"TRACK_CARGO": ["Capacity", "Capacidad", "Kapazität", "Capacité", "積載量", "载货量", "적재량",
    "Capacity", "Capacity", "Capacity", "Load capacity", "Cargo capacity", "Load capacity"],
"TRACK_DOG_STRENGTH": ["Carry", "Porte", "Tragen", "Portage", "運搬", "搬运", "운반",
    "Carrying", "Carry", "Carrying", "Transport", "Carrying", "Transport"],
"TRACK_LUCKY_HAUL": ["Luck", "Suerte", "Glück", "Chance", "ラッキー", "幸运", "행운",
    "Luck", "Luck", "Luck", "Lucky", "Luck", "Luck"],
"TRACK_NET_WIDTH": ["Size", "Tamaño", "Größe", "Taille", "大きさ", "大小", "크기",
    "Size", "Size", "Size", "Size", "Size", "Size"],
"TRACK_RECYCLE_BONUS": ["$ Bonus", "$ Bono", "$ Bonus", "$ Bonus", "$ ボーナス", "$ 奖励", "$ 보너스",
    "$ Bonus", "$ Bonus", "$ Bonus", "$ Bonus", "$ Reward", "$ Bonus"],
"TRACK_REEL": ["Reel", "Recogida", "Einholen", "Remontée", "巻き取り", "收网", "감기",
    "Reeling in", "Hauling in", "Reeling in", "Reeling", "Reeling in", "Reeling"],
"TROPHY_FOUND": ["Found a decoration!", "¡Encontraste una decoración!", "Deko gefunden!", "Une décoration trouvée !",
    "飾りを見つけた！", "找到一件装饰！", "장식을 찾았어요!",
    "You found a decoration!", "Decoration found!", "A decoration found!", "Found a decoration!", "Found a decoration!", "Found a decoration!"],
"VERB_OPEN_SHED": ["Open the house", "Abrir la casa", "Haus öffnen", "Ouvrir la maison", "家を開く", "打开房子", "집 열기",
    "Open the house", "Open house", "Open the house", "Open the house", "Open the house", "Open the house"],
"VERB_SHED_ROTATE": ["Turn the decoration", "Girar la decoración", "Deko drehen", "Tourner la déco", "飾りを回す", "旋转装饰", "장식 돌리기",
    "Turn the decoration", "Turn decoration", "Turn the decoration", "Turn the decoration", "Rotate decoration", "Rotate decoration"],
"WASH_EMPTY_1": ["Nothing available.", "Nada disponible.", "Nichts da.", "Rien de dispo.", "何もありません。", "暂无可洗。", "없어요.",
    "Nothing available.", "Nothing here.", "Nothing available.", "There is nothing.", "Nothing to wash.", "Nothing."],
"WASH_EMPTY_2": ["Find decorations and", "Encuentra decoraciones", "Finde Deko und", "Trouve des décos", "飾りを見つけて", "找到装饰后", "장식을 찾아서",
    "Find decorations and", "Find decorations", "Find decorations", "Find decorations and", "After finding decorations", "Find decorations and"],
"WASH_EMPTY_3": ["wash them here.", "y lávalas aquí.", "wasche sie hier.", "et lave-les ici.", "ここで洗おう。", "来这里清洗。", "여기서 씻어요.",
    "and wash them here.", "wash them here.", "and wash them here.", "Wash them here.", "come here to wash them.", "wash them here."],
"WASH_WASHING": ["Washing", "Lavando", "Wäscht", "Lavage", "洗浄中", "清洗中", "세척 중",
    "Washing", "Washing", "Washing", "Washing", "Washing", "Washing"],
"WILDLIFE_BACK": ["Wildlife is coming back, great news!\nKeep up the good work.",
    "¡La vida silvestre está volviendo, buenas noticias!\nSigue así.",
    "Die Tiere kehren zurück, tolle Neuigkeit!\nMach weiter so.",
    "La faune revient, excellente nouvelle !\nContinue comme ça.",
    "野生の生き物が戻ってきた、うれしい知らせ！\nこの調子で続けよう。",
    "野生动物回来了，好消息！\n继续加油。",
    "야생 동물이 돌아오고 있어요, 좋은 소식이에요!\n계속 힘내요.",
    "Wildlife is coming back, good news!\nKeep it up.", "The animals are coming back, great news!\nKeep it up.",
    "The wildlife is returning, excellent news!\nKeep it up.", "Wild creatures are back, happy news!\nKeep it up.",
    "Wildlife is back, good news!\nKeep it up.", "Wildlife is coming back, good news!\nKeep it up."],
}

# His Portuguese, with the fixes the pass needs: the trailing space the greeting's two runs are
# drawn apart by, the key in the room card as a placeholder, and two small grammar slips.
PT_FIX = {
    "LETTER_GREETING_LEAD": "Você é o mais novo proprietário do ",
    "TOUR_DECOR_ROOM": "Você pode interagir com alguns objetos apertando %s. Aparece quando der.",
    "LETTER_DECOR_LINE": "Algumas pescas são decoração para a sua casa.",
    "TOUR_SHOP_ON_CAST": "Melhorias também aumentam a chance de redes da sorte ou de lançamento duplo.",
}
DROP = {"CONSOLE_COUNT", "SETTINGS_WIPE", "WASH_SOAP"}
LANGS = ["en", "es", "de", "fr", "ja", "zh_CN", "ko"]
BACKS = ["_back_es", "_back_de", "_back_fr", "_back_ja", "_back_zh_CN", "_back_ko"]

edits = {}
for f in glob.glob("tools/ptdb/pt/*.json"):
    d = json.load(open(f, encoding="utf-8"))
    edits[os.path.basename(f)[:-5]] = d

with open("locale/translations.csv", encoding="utf-8", newline="") as fh:
    reader = csv.DictReader(fh)
    fields = reader.fieldnames
    rows = list(reader)

out = []
for r in rows:
    k = r["keys"]
    if k in DROP:
        continue
    if k in edits and isinstance(edits[k].get("pt"), str):
        r["pt_BR"] = PT_FIX.get(k, edits[k]["pt"].rstrip())
        if k in T:
            vals = T[k]
            assert len(vals) == 13, k
            for c, v in zip(LANGS + BACKS, vals):
                r[c] = v
            r["_back_pt_BR"] = vals[0]
        else:
            print("pt changed, no retranslation:", k)
    out.append(r)

with open("locale/translations.csv", "w", encoding="utf-8", newline="") as fh:
    w = csv.DictWriter(fh, fieldnames=fields, lineterminator="\n")
    w.writeheader()
    w.writerows(out)
print(len(rows), "->", len(out))
