## Every word the game shows, one getter a key of `locale/translations.csv`.
## GENERATED by `tools/build_translations.py`: do not edit by hand.
##
## Each getter asks `TranslationServer` in the language in play, so a board that draws
## `Text.KEY` in `_draw` follows a language change on its next redraw.
class_name Text


## One key by its name, for keys picked at runtime (a find's title).
static func of(key: String) -> String:
	return TranslationServer.translate(StringName(key))


static var MENU_CONTINUE: String:
	get: return TranslationServer.translate(&"MENU_CONTINUE")

static var MENU_NEW: String:
	get: return TranslationServer.translate(&"MENU_NEW")

static var MENU_SETTINGS: String:
	get: return TranslationServer.translate(&"MENU_SETTINGS")

static var MENU_HOW: String:
	get: return TranslationServer.translate(&"MENU_HOW")

static var MENU_CREDITS: String:
	get: return TranslationServer.translate(&"MENU_CREDITS")

static var MENU_QUIT: String:
	get: return TranslationServer.translate(&"MENU_QUIT")

static var LANGUAGE_TITLE: String:
	get: return TranslationServer.translate(&"LANGUAGE_TITLE")

static var CONFIRM_NEW_TITLE: String:
	get: return TranslationServer.translate(&"CONFIRM_NEW_TITLE")

static var CONFIRM_NEW_WORDS: String:
	get: return TranslationServer.translate(&"CONFIRM_NEW_WORDS")

static var CONFIRM_NEW_YES: String:
	get: return TranslationServer.translate(&"CONFIRM_NEW_YES")

static var CONFIRM_NEW_NO: String:
	get: return TranslationServer.translate(&"CONFIRM_NEW_NO")

static var SETTINGS_TITLE: String:
	get: return TranslationServer.translate(&"SETTINGS_TITLE")

static var SETTINGS_MASTER: String:
	get: return TranslationServer.translate(&"SETTINGS_MASTER")

static var SETTINGS_MUSIC: String:
	get: return TranslationServer.translate(&"SETTINGS_MUSIC")

static var SETTINGS_SFX: String:
	get: return TranslationServer.translate(&"SETTINGS_SFX")

static var SETTINGS_AMBIENCE: String:
	get: return TranslationServer.translate(&"SETTINGS_AMBIENCE")

static var SETTINGS_WINDOW: String:
	get: return TranslationServer.translate(&"SETTINGS_WINDOW")

static var SETTINGS_RESOLUTION: String:
	get: return TranslationServer.translate(&"SETTINGS_RESOLUTION")

static var SETTINGS_VSYNC: String:
	get: return TranslationServer.translate(&"SETTINGS_VSYNC")

static var SETTINGS_FPS: String:
	get: return TranslationServer.translate(&"SETTINGS_FPS")

static var SETTINGS_GROUP_MIX: String:
	get: return TranslationServer.translate(&"SETTINGS_GROUP_MIX")

static var SETTINGS_GROUP_SCREEN: String:
	get: return TranslationServer.translate(&"SETTINGS_GROUP_SCREEN")

static var SETTINGS_CONTROLS: String:
	get: return TranslationServer.translate(&"SETTINGS_CONTROLS")

static var SETTINGS_QUIT: String:
	get: return TranslationServer.translate(&"SETTINGS_QUIT")

static var SETTINGS_DEAD_SIZE: String:
	get: return TranslationServer.translate(&"SETTINGS_DEAD_SIZE")

static var WINDOW_WINDOWED: String:
	get: return TranslationServer.translate(&"WINDOW_WINDOWED")

static var WINDOW_BORDERLESS: String:
	get: return TranslationServer.translate(&"WINDOW_BORDERLESS")

static var WINDOW_EXCLUSIVE: String:
	get: return TranslationServer.translate(&"WINDOW_EXCLUSIVE")

static var VSYNC_OFF: String:
	get: return TranslationServer.translate(&"VSYNC_OFF")

static var VSYNC_ON: String:
	get: return TranslationServer.translate(&"VSYNC_ON")

static var VSYNC_ADAPTIVE: String:
	get: return TranslationServer.translate(&"VSYNC_ADAPTIVE")

static var FPS_UNCAPPED: String:
	get: return TranslationServer.translate(&"FPS_UNCAPPED")

static var KEEP_MODE_TITLE: String:
	get: return TranslationServer.translate(&"KEEP_MODE_TITLE")

static var KEEP_MODE_YES: String:
	get: return TranslationServer.translate(&"KEEP_MODE_YES")

static var KEEP_MODE_NO: String:
	get: return TranslationServer.translate(&"KEEP_MODE_NO")

static var KEEP_MODE_WORDS: String:
	get: return TranslationServer.translate(&"KEEP_MODE_WORDS")

static var CONTROLS_TITLE: String:
	get: return TranslationServer.translate(&"CONTROLS_TITLE")

static var CONTROLS_DEFAULT: String:
	get: return TranslationServer.translate(&"CONTROLS_DEFAULT")

static var CONTROLS_CAPTURING: String:
	get: return TranslationServer.translate(&"CONTROLS_CAPTURING")

static var CONTROLS_COL_KEY: String:
	get: return TranslationServer.translate(&"CONTROLS_COL_KEY")

static var CONTROLS_COL_PAD: String:
	get: return TranslationServer.translate(&"CONTROLS_COL_PAD")

static var CONTROLS_HINT: String:
	get: return TranslationServer.translate(&"CONTROLS_HINT")

static var CONTROLS_HINT_PAD: String:
	get: return TranslationServer.translate(&"CONTROLS_HINT_PAD")

static var CONTROLS_PROMPTS_AUTO: String:
	get: return TranslationServer.translate(&"CONTROLS_PROMPTS_AUTO")

static var CONTROLS_MOVED: String:
	get: return TranslationServer.translate(&"CONTROLS_MOVED")

static var CONFIRM_BINDS_TITLE: String:
	get: return TranslationServer.translate(&"CONFIRM_BINDS_TITLE")

static var CONFIRM_BINDS_YES: String:
	get: return TranslationServer.translate(&"CONFIRM_BINDS_YES")

static var CONFIRM_BINDS_NO: String:
	get: return TranslationServer.translate(&"CONFIRM_BINDS_NO")

static var VERB_WALK_UP: String:
	get: return TranslationServer.translate(&"VERB_WALK_UP")

static var VERB_WALK_DOWN: String:
	get: return TranslationServer.translate(&"VERB_WALK_DOWN")

static var VERB_WALK_LEFT: String:
	get: return TranslationServer.translate(&"VERB_WALK_LEFT")

static var VERB_WALK_RIGHT: String:
	get: return TranslationServer.translate(&"VERB_WALK_RIGHT")

static var VERB_CAST: String:
	get: return TranslationServer.translate(&"VERB_CAST")

static var VERB_INTERACT: String:
	get: return TranslationServer.translate(&"VERB_INTERACT")

static var VERB_OPEN_SHED: String:
	get: return TranslationServer.translate(&"VERB_OPEN_SHED")

static var VERB_OPEN_UPGRADES: String:
	get: return TranslationServer.translate(&"VERB_OPEN_UPGRADES")

static var VERB_OPEN_SETTINGS: String:
	get: return TranslationServer.translate(&"VERB_OPEN_SETTINGS")

static var VERB_ZOOM_IN: String:
	get: return TranslationServer.translate(&"VERB_ZOOM_IN")

static var VERB_ZOOM_OUT: String:
	get: return TranslationServer.translate(&"VERB_ZOOM_OUT")

static var VERB_RECENTRE: String:
	get: return TranslationServer.translate(&"VERB_RECENTRE")

static var VERB_CAMERA_PAN: String:
	get: return TranslationServer.translate(&"VERB_CAMERA_PAN")

static var VERB_CAMERA_LOCK: String:
	get: return TranslationServer.translate(&"VERB_CAMERA_LOCK")

static var VERB_SHED_ROTATE: String:
	get: return TranslationServer.translate(&"VERB_SHED_ROTATE")

static var VERB_SHED_SWITCH: String:
	get: return TranslationServer.translate(&"VERB_SHED_SWITCH")

static var BIND_GROUP_MOVE: String:
	get: return TranslationServer.translate(&"BIND_GROUP_MOVE")

static var BIND_GROUP_NET: String:
	get: return TranslationServer.translate(&"BIND_GROUP_NET")

static var BIND_GROUP_OPEN: String:
	get: return TranslationServer.translate(&"BIND_GROUP_OPEN")

static var BIND_GROUP_VIEW: String:
	get: return TranslationServer.translate(&"BIND_GROUP_VIEW")

static var BIND_GROUP_SHED: String:
	get: return TranslationServer.translate(&"BIND_GROUP_SHED")

static var BIND_STICK: String:
	get: return TranslationServer.translate(&"BIND_STICK")

static var SHOP_BOARD_NET: String:
	get: return TranslationServer.translate(&"SHOP_BOARD_NET")

static var SHOP_BOARD_BOATS: String:
	get: return TranslationServer.translate(&"SHOP_BOARD_BOATS")

static var SHOP_BOARD_DOGS: String:
	get: return TranslationServer.translate(&"SHOP_BOARD_DOGS")

static var SHOP_BOARD_LUCK: String:
	get: return TranslationServer.translate(&"SHOP_BOARD_LUCK")

static var SHOP_GROUP_RUN: String:
	get: return TranslationServer.translate(&"SHOP_GROUP_RUN")

static var SHOP_GROUP_FLEET: String:
	get: return TranslationServer.translate(&"SHOP_GROUP_FLEET")

static var SHOP_GROUP_PACK: String:
	get: return TranslationServer.translate(&"SHOP_GROUP_PACK")

static var SHOP_GROUP_TRIP: String:
	get: return TranslationServer.translate(&"SHOP_GROUP_TRIP")

static var SHOP_GROUP_ON_CAST: String:
	get: return TranslationServer.translate(&"SHOP_GROUP_ON_CAST")

static var SHOP_GROUP_AT_YARDS: String:
	get: return TranslationServer.translate(&"SHOP_GROUP_AT_YARDS")

static var TRACK_NET_WIDTH: String:
	get: return TranslationServer.translate(&"TRACK_NET_WIDTH")

static var TRACK_NET_STRENGTH: String:
	get: return TranslationServer.translate(&"TRACK_NET_STRENGTH")

static var TRACK_NET_RANGE: String:
	get: return TranslationServer.translate(&"TRACK_NET_RANGE")

static var TRACK_REEL: String:
	get: return TranslationServer.translate(&"TRACK_REEL")

static var TRACK_NET_HOLD: String:
	get: return TranslationServer.translate(&"TRACK_NET_HOLD")

static var TRACK_BOAT_SPEED: String:
	get: return TranslationServer.translate(&"TRACK_BOAT_SPEED")

static var TRACK_CARGO: String:
	get: return TranslationServer.translate(&"TRACK_CARGO")

static var TRACK_BOAT_VOLLEY: String:
	get: return TranslationServer.translate(&"TRACK_BOAT_VOLLEY")

static var TRACK_FLEET: String:
	get: return TranslationServer.translate(&"TRACK_FLEET")

static var TRACK_DOG_COUNT: String:
	get: return TranslationServer.translate(&"TRACK_DOG_COUNT")

static var TRACK_DOG_STRENGTH: String:
	get: return TranslationServer.translate(&"TRACK_DOG_STRENGTH")

static var TRACK_DOG_FETCH: String:
	get: return TranslationServer.translate(&"TRACK_DOG_FETCH")

static var TRACK_DOG_WAIT: String:
	get: return TranslationServer.translate(&"TRACK_DOG_WAIT")

static var TRACK_RECYCLE_BONUS: String:
	get: return TranslationServer.translate(&"TRACK_RECYCLE_BONUS")

static var TRACK_BIRD_WORTH: String:
	get: return TranslationServer.translate(&"TRACK_BIRD_WORTH")

static var TRACK_LUCKY_HAUL: String:
	get: return TranslationServer.translate(&"TRACK_LUCKY_HAUL")

static var TRACK_DOUBLE_CAST: String:
	get: return TranslationServer.translate(&"TRACK_DOUBLE_CAST")

static var BLURB_NET_WIDTH: String:
	get: return TranslationServer.translate(&"BLURB_NET_WIDTH")

static var BLURB_NET_STRENGTH: String:
	get: return TranslationServer.translate(&"BLURB_NET_STRENGTH")

static var BLURB_NET_RANGE: String:
	get: return TranslationServer.translate(&"BLURB_NET_RANGE")

static var BLURB_REEL: String:
	get: return TranslationServer.translate(&"BLURB_REEL")

static var BLURB_NET_HOLD: String:
	get: return TranslationServer.translate(&"BLURB_NET_HOLD")

static var BLURB_BOAT_SPEED: String:
	get: return TranslationServer.translate(&"BLURB_BOAT_SPEED")

static var BLURB_CARGO: String:
	get: return TranslationServer.translate(&"BLURB_CARGO")

static var BLURB_BOAT_VOLLEY: String:
	get: return TranslationServer.translate(&"BLURB_BOAT_VOLLEY")

static var BLURB_FLEET: String:
	get: return TranslationServer.translate(&"BLURB_FLEET")

static var BLURB_DOG_COUNT: String:
	get: return TranslationServer.translate(&"BLURB_DOG_COUNT")

static var BLURB_DOG_STRENGTH: String:
	get: return TranslationServer.translate(&"BLURB_DOG_STRENGTH")

static var BLURB_DOG_FETCH: String:
	get: return TranslationServer.translate(&"BLURB_DOG_FETCH")

static var BLURB_DOG_WAIT: String:
	get: return TranslationServer.translate(&"BLURB_DOG_WAIT")

static var BLURB_RECYCLE_BONUS: String:
	get: return TranslationServer.translate(&"BLURB_RECYCLE_BONUS")

static var BLURB_BIRD_WORTH: String:
	get: return TranslationServer.translate(&"BLURB_BIRD_WORTH")

static var BLURB_LUCKY_HAUL: String:
	get: return TranslationServer.translate(&"BLURB_LUCKY_HAUL")

static var BLURB_DOUBLE_CAST: String:
	get: return TranslationServer.translate(&"BLURB_DOUBLE_CAST")

static var SHOP_TIER_PREFIX: String:
	get: return TranslationServer.translate(&"SHOP_TIER_PREFIX")

static var SHOP_MAX: String:
	get: return TranslationServer.translate(&"SHOP_MAX")

static var SHOP_LEGEND: String:
	get: return TranslationServer.translate(&"SHOP_LEGEND")

static var SHOP_BONUS_LINE: String:
	get: return TranslationServer.translate(&"SHOP_BONUS_LINE")

static var HUD_WAITING: String:
	get: return TranslationServer.translate(&"HUD_WAITING")

static var HUD_UPGRADES: String:
	get: return TranslationServer.translate(&"HUD_UPGRADES")

static var HUD_DECORATE: String:
	get: return TranslationServer.translate(&"HUD_DECORATE")

static var HUD_PIECES_LEFT_1: String:
	get: return TranslationServer.translate(&"HUD_PIECES_LEFT_1")

static var HUD_PIECES_LEFT_N: String:
	get: return TranslationServer.translate(&"HUD_PIECES_LEFT_N")

static var SHELF_TITLE: String:
	get: return TranslationServer.translate(&"SHELF_TITLE")

static var SHELF_TITLE_N: String:
	get: return TranslationServer.translate(&"SHELF_TITLE_N")

static var SHELF_EMPTY: String:
	get: return TranslationServer.translate(&"SHELF_EMPTY")

static var SHELF_WASH_N: String:
	get: return TranslationServer.translate(&"SHELF_WASH_N")

static var LETTER_TITLE: String:
	get: return TranslationServer.translate(&"LETTER_TITLE")

static var LETTER_NET_HEAD: String:
	get: return TranslationServer.translate(&"LETTER_NET_HEAD")

static var LETTER_NET_GREEN: String:
	get: return TranslationServer.translate(&"LETTER_NET_GREEN")

static var LETTER_NET_RED: String:
	get: return TranslationServer.translate(&"LETTER_NET_RED")

static var LETTER_NET_WHITE: String:
	get: return TranslationServer.translate(&"LETTER_NET_WHITE")

static var LETTER_UPGRADES_HEAD: String:
	get: return TranslationServer.translate(&"LETTER_UPGRADES_HEAD")

static var LETTER_WEIGHT_HEAD: String:
	get: return TranslationServer.translate(&"LETTER_WEIGHT_HEAD")

static var LETTER_WEIGHT_CAP1: String:
	get: return TranslationServer.translate(&"LETTER_WEIGHT_CAP1")

static var LETTER_WEIGHT_CAP2: String:
	get: return TranslationServer.translate(&"LETTER_WEIGHT_CAP2")

static var LETTER_DECOR_HEAD: String:
	get: return TranslationServer.translate(&"LETTER_DECOR_HEAD")

static var LETTER_DECOR_LINE: String:
	get: return TranslationServer.translate(&"LETTER_DECOR_LINE")

static var LETTER_DECOR_CAP1: String:
	get: return TranslationServer.translate(&"LETTER_DECOR_CAP1")

static var LETTER_DECOR_CAP2: String:
	get: return TranslationServer.translate(&"LETTER_DECOR_CAP2")

static var LETTER_DECOR_CAP3: String:
	get: return TranslationServer.translate(&"LETTER_DECOR_CAP3")

static var LETTER_START: String:
	get: return TranslationServer.translate(&"LETTER_START")

static var WASH_TITLE: String:
	get: return TranslationServer.translate(&"WASH_TITLE")

static var WASH_EMPTY_1: String:
	get: return TranslationServer.translate(&"WASH_EMPTY_1")

static var WASH_EMPTY_2: String:
	get: return TranslationServer.translate(&"WASH_EMPTY_2")

static var WASH_EMPTY_3: String:
	get: return TranslationServer.translate(&"WASH_EMPTY_3")

static var END_LINE_1: String:
	get: return TranslationServer.translate(&"END_LINE_1")

static var END_LINE_2: String:
	get: return TranslationServer.translate(&"END_LINE_2")

static var END_BACK: String:
	get: return TranslationServer.translate(&"END_BACK")

static var MATERIAL_PLASTIC: String:
	get: return TranslationServer.translate(&"MATERIAL_PLASTIC")

static var MATERIAL_WOOD: String:
	get: return TranslationServer.translate(&"MATERIAL_WOOD")

static var MATERIAL_METAL: String:
	get: return TranslationServer.translate(&"MATERIAL_METAL")

static var MATERIAL_RUBBER: String:
	get: return TranslationServer.translate(&"MATERIAL_RUBBER")

static var TROPHY_FOUND: String:
	get: return TranslationServer.translate(&"TROPHY_FOUND")

static var CREDITS_TITLE: String:
	get: return TranslationServer.translate(&"CREDITS_TITLE")

static var CREDITS_HEAD_DESIGN: String:
	get: return TranslationServer.translate(&"CREDITS_HEAD_DESIGN")

static var CREDITS_HEAD_MUSIC: String:
	get: return TranslationServer.translate(&"CREDITS_HEAD_MUSIC")

static var CREDITS_HEAD_ART: String:
	get: return TranslationServer.translate(&"CREDITS_HEAD_ART")

static var CREDITS_HEAD_TOOLS: String:
	get: return TranslationServer.translate(&"CREDITS_HEAD_TOOLS")

static var DECOR_SOFA: String:
	get: return TranslationServer.translate(&"DECOR_SOFA")

static var DECOR_LOVESEAT: String:
	get: return TranslationServer.translate(&"DECOR_LOVESEAT")

static var DECOR_DINING_CHAIR: String:
	get: return TranslationServer.translate(&"DECOR_DINING_CHAIR")

static var DECOR_DRESSER: String:
	get: return TranslationServer.translate(&"DECOR_DRESSER")

static var DECOR_NIGHTSTAND: String:
	get: return TranslationServer.translate(&"DECOR_NIGHTSTAND")

static var DECOR_BOOKCASE_DRAWERS: String:
	get: return TranslationServer.translate(&"DECOR_BOOKCASE_DRAWERS")

static var DECOR_BOOKCASE_TALL: String:
	get: return TranslationServer.translate(&"DECOR_BOOKCASE_TALL")

static var DECOR_BIG_TABLE: String:
	get: return TranslationServer.translate(&"DECOR_BIG_TABLE")

static var DECOR_SIDE_DESK: String:
	get: return TranslationServer.translate(&"DECOR_SIDE_DESK")

static var DECOR_KITCHEN_COUNTER: String:
	get: return TranslationServer.translate(&"DECOR_KITCHEN_COUNTER")

static var DECOR_TOILET: String:
	get: return TranslationServer.translate(&"DECOR_TOILET")

static var DECOR_BIG_RUG: String:
	get: return TranslationServer.translate(&"DECOR_BIG_RUG")

static var DECOR_OLD_RUG: String:
	get: return TranslationServer.translate(&"DECOR_OLD_RUG")

static var DECOR_FIREPLACE: String:
	get: return TranslationServer.translate(&"DECOR_FIREPLACE")

static var DECOR_FRIDGE: String:
	get: return TranslationServer.translate(&"DECOR_FRIDGE")

static var DECOR_PET_BED: String:
	get: return TranslationServer.translate(&"DECOR_PET_BED")

static var DECOR_BED: String:
	get: return TranslationServer.translate(&"DECOR_BED")

static var DECOR_LAMP: String:
	get: return TranslationServer.translate(&"DECOR_LAMP")

static var DECOR_STANDING_LAMP: String:
	get: return TranslationServer.translate(&"DECOR_STANDING_LAMP")

static var DECOR_OLD_CLOCK: String:
	get: return TranslationServer.translate(&"DECOR_OLD_CLOCK")

static var DECOR_COAT_HANGER: String:
	get: return TranslationServer.translate(&"DECOR_COAT_HANGER")

static var DECOR_MIRROR: String:
	get: return TranslationServer.translate(&"DECOR_MIRROR")

static var DECOR_STOVE: String:
	get: return TranslationServer.translate(&"DECOR_STOVE")

static var DECOR_VYNIL_PLAYER: String:
	get: return TranslationServer.translate(&"DECOR_VYNIL_PLAYER")

static var DECOR_BATH_SINK: String:
	get: return TranslationServer.translate(&"DECOR_BATH_SINK")

static var DECOR_BATHTUB: String:
	get: return TranslationServer.translate(&"DECOR_BATHTUB")

static var DECOR_IRON_BOARD: String:
	get: return TranslationServer.translate(&"DECOR_IRON_BOARD")

static var DECOR_CENTER_TABLE: String:
	get: return TranslationServer.translate(&"DECOR_CENTER_TABLE")

static var DECOR_GAME_TABLE: String:
	get: return TranslationServer.translate(&"DECOR_GAME_TABLE")

static var DECOR_TINY_BOOKCASE: String:
	get: return TranslationServer.translate(&"DECOR_TINY_BOOKCASE")

static var DECOR_OVAL_RUG: String:
	get: return TranslationServer.translate(&"DECOR_OVAL_RUG")

static var DECOR_FLOWER_POT: String:
	get: return TranslationServer.translate(&"DECOR_FLOWER_POT")

static var DECOR_PLANT_POT: String:
	get: return TranslationServer.translate(&"DECOR_PLANT_POT")

static var DECOR_PAINTING_A: String:
	get: return TranslationServer.translate(&"DECOR_PAINTING_A")

static var DECOR_PAINTING_B: String:
	get: return TranslationServer.translate(&"DECOR_PAINTING_B")

static var DECOR_CHEW_TOY: String:
	get: return TranslationServer.translate(&"DECOR_CHEW_TOY")

static var DECOR_GLOBE: String:
	get: return TranslationServer.translate(&"DECOR_GLOBE")

static var DECOR_RUG: String:
	get: return TranslationServer.translate(&"DECOR_RUG")

static var DECOR_AQUARIUM: String:
	get: return TranslationServer.translate(&"DECOR_AQUARIUM")

static var HUD_AVAILABLE: String:
	get: return TranslationServer.translate(&"HUD_AVAILABLE")

static var STEPS_NOTE: String:
	get: return TranslationServer.translate(&"STEPS_NOTE")

static var TOUR_SKIP: String:
	get: return TranslationServer.translate(&"TOUR_SKIP")

static var TOUR_CONTINUE: String:
	get: return TranslationServer.translate(&"TOUR_CONTINUE")

static var TOUR_DECOR_HINT: String:
	get: return TranslationServer.translate(&"TOUR_DECOR_HINT")

static var TOUR_DECOR_HINT_PAD: String:
	get: return TranslationServer.translate(&"TOUR_DECOR_HINT_PAD")

static var TOUR_DECOR_PLANK: String:
	get: return TranslationServer.translate(&"TOUR_DECOR_PLANK")

static var TOUR_DECOR_LIST: String:
	get: return TranslationServer.translate(&"TOUR_DECOR_LIST")

static var TOUR_DECOR_STAND: String:
	get: return TranslationServer.translate(&"TOUR_DECOR_STAND")

static var TOUR_DECOR_STAND_PAD: String:
	get: return TranslationServer.translate(&"TOUR_DECOR_STAND_PAD")

static var TOUR_DECOR_SHELF: String:
	get: return TranslationServer.translate(&"TOUR_DECOR_SHELF")

static var TOUR_DECOR_SHELF_PAD: String:
	get: return TranslationServer.translate(&"TOUR_DECOR_SHELF_PAD")

static var TOUR_DECOR_ROOM: String:
	get: return TranslationServer.translate(&"TOUR_DECOR_ROOM")

static var UI_CLOSE: String:
	get: return TranslationServer.translate(&"UI_CLOSE")

static var TOUR_SHOP_NET: String:
	get: return TranslationServer.translate(&"TOUR_SHOP_NET")

static var TOUR_SHOP_ON_CAST: String:
	get: return TranslationServer.translate(&"TOUR_SHOP_ON_CAST")

static var TOUR_SHOP_BOATS: String:
	get: return TranslationServer.translate(&"TOUR_SHOP_BOATS")

static var TOUR_SHOP_DOGS: String:
	get: return TranslationServer.translate(&"TOUR_SHOP_DOGS")

static var TOUR_SHOP_AT_YARDS: String:
	get: return TranslationServer.translate(&"TOUR_SHOP_AT_YARDS")

static var TOUR_SHOP_LEGEND: String:
	get: return TranslationServer.translate(&"TOUR_SHOP_LEGEND")

static var LETTER_WELCOME_TITLE: String:
	get: return TranslationServer.translate(&"LETTER_WELCOME_TITLE")

static var LETTER_GREETING_LEAD: String:
	get: return TranslationServer.translate(&"LETTER_GREETING_LEAD")

static var LETTER_GAME_NAME: String:
	get: return TranslationServer.translate(&"LETTER_GAME_NAME")

static var LETTER_WELCOME_TEXT: String:
	get: return TranslationServer.translate(&"LETTER_WELCOME_TEXT")

static var LETTER_NET_TEXT: String:
	get: return TranslationServer.translate(&"LETTER_NET_TEXT")

static var LETTER_NET_TEXT_PAD: String:
	get: return TranslationServer.translate(&"LETTER_NET_TEXT_PAD")

static var LETTER_UPGRADES_NET: String:
	get: return TranslationServer.translate(&"LETTER_UPGRADES_NET")

static var LETTER_UPGRADES_BOATS: String:
	get: return TranslationServer.translate(&"LETTER_UPGRADES_BOATS")

static var LETTER_UPGRADES_DOGS: String:
	get: return TranslationServer.translate(&"LETTER_UPGRADES_DOGS")

static var LETTER_WEIGHT_TEXT: String:
	get: return TranslationServer.translate(&"LETTER_WEIGHT_TEXT")

static var CREDITS_GODOT: String:
	get: return TranslationServer.translate(&"CREDITS_GODOT")

static var WASH_TITLE_N: String:
	get: return TranslationServer.translate(&"WASH_TITLE_N")

static var WASH_FREE: String:
	get: return TranslationServer.translate(&"WASH_FREE")

static var WASH_WASHING: String:
	get: return TranslationServer.translate(&"WASH_WASHING")

static var WILDLIFE_BACK: String:
	get: return TranslationServer.translate(&"WILDLIFE_BACK")

static var RECORD_SONG: String:
	get: return TranslationServer.translate(&"RECORD_SONG")

static var RECORD_LAKE: String:
	get: return TranslationServer.translate(&"RECORD_LAKE")

static var RECORD_SHED: String:
	get: return TranslationServer.translate(&"RECORD_SHED")

static var RECORD_NOW: String:
	get: return TranslationServer.translate(&"RECORD_NOW")

static var RECORD_SYNC: String:
	get: return TranslationServer.translate(&"RECORD_SYNC")

static var HIVE_SWARM: String:
	get: return TranslationServer.translate(&"HIVE_SWARM")

static var HIVE_STEP_CATCH: String:
	get: return TranslationServer.translate(&"HIVE_STEP_CATCH")

static var HIVE_STEP_SMOKE: String:
	get: return TranslationServer.translate(&"HIVE_STEP_SMOKE")

static var HIVE_STEP_QUEEN: String:
	get: return TranslationServer.translate(&"HIVE_STEP_QUEEN")

static var HIVE_STEP_UNCAP: String:
	get: return TranslationServer.translate(&"HIVE_STEP_UNCAP")

static var HIVE_STEP_POUR: String:
	get: return TranslationServer.translate(&"HIVE_STEP_POUR")

static var HIVE_HINT_CATCH: String:
	get: return TranslationServer.translate(&"HIVE_HINT_CATCH")

static var HIVE_HINT_SMOKE: String:
	get: return TranslationServer.translate(&"HIVE_HINT_SMOKE")

static var HIVE_HINT_QUEEN: String:
	get: return TranslationServer.translate(&"HIVE_HINT_QUEEN")

static var HIVE_HINT_UNCAP: String:
	get: return TranslationServer.translate(&"HIVE_HINT_UNCAP")

static var HIVE_HINT_POUR: String:
	get: return TranslationServer.translate(&"HIVE_HINT_POUR")

static var HIVE_HINT_DONE: String:
	get: return TranslationServer.translate(&"HIVE_HINT_DONE")

static var HIVE_HINT_SETTLED: String:
	get: return TranslationServer.translate(&"HIVE_HINT_SETTLED")

static var HIVE_READY: String:
	get: return TranslationServer.translate(&"HIVE_READY")

static var HOSE_NAME: String:
	get: return TranslationServer.translate(&"HOSE_NAME")

static var DECOR_PK_ARMCHAIR: String:
	get: return TranslationServer.translate(&"DECOR_PK_ARMCHAIR")

static var DECOR_PK_OLD_SEAT: String:
	get: return TranslationServer.translate(&"DECOR_PK_OLD_SEAT")

static var DECOR_PK_BATHTUB: String:
	get: return TranslationServer.translate(&"DECOR_PK_BATHTUB")

static var DECOR_PK_BED: String:
	get: return TranslationServer.translate(&"DECOR_PK_BED")

static var DECOR_PK_BOOKSHELF: String:
	get: return TranslationServer.translate(&"DECOR_PK_BOOKSHELF")

static var DECOR_PK_CHAIR: String:
	get: return TranslationServer.translate(&"DECOR_PK_CHAIR")

static var DECOR_PK_COFFEE_TABLE: String:
	get: return TranslationServer.translate(&"DECOR_PK_COFFEE_TABLE")

static var DECOR_PK_CORNER_DESK: String:
	get: return TranslationServer.translate(&"DECOR_PK_CORNER_DESK")

static var DECOR_PK_DRAWER: String:
	get: return TranslationServer.translate(&"DECOR_PK_DRAWER")

static var DECOR_PK_DRAWER_DESK: String:
	get: return TranslationServer.translate(&"DECOR_PK_DRAWER_DESK")

static var DECOR_PK_FANCY_BED: String:
	get: return TranslationServer.translate(&"DECOR_PK_FANCY_BED")

static var DECOR_PK_FANCY_TABLE: String:
	get: return TranslationServer.translate(&"DECOR_PK_FANCY_TABLE")

static var DECOR_PK_FILE_CABINET: String:
	get: return TranslationServer.translate(&"DECOR_PK_FILE_CABINET")

static var DECOR_PK_FIREPLACE: String:
	get: return TranslationServer.translate(&"DECOR_PK_FIREPLACE")

static var DECOR_PK_KITCHEN_COUNTER: String:
	get: return TranslationServer.translate(&"DECOR_PK_KITCHEN_COUNTER")

static var DECOR_PK_MICROWAVE: String:
	get: return TranslationServer.translate(&"DECOR_PK_MICROWAVE")

static var DECOR_PK_SOFA: String:
	get: return TranslationServer.translate(&"DECOR_PK_SOFA")

static var DECOR_PK_STOVE: String:
	get: return TranslationServer.translate(&"DECOR_PK_STOVE")

static var DECOR_PK_TABLE: String:
	get: return TranslationServer.translate(&"DECOR_PK_TABLE")

static var DECOR_PK_TOILET: String:
	get: return TranslationServer.translate(&"DECOR_PK_TOILET")

static var DECOR_PK_DINER_CHAIR: String:
	get: return TranslationServer.translate(&"DECOR_PK_DINER_CHAIR")

static var DECOR_PK_GREEN_CHAIR: String:
	get: return TranslationServer.translate(&"DECOR_PK_GREEN_CHAIR")

static var DECOR_PK_WOOD_CHAIR: String:
	get: return TranslationServer.translate(&"DECOR_PK_WOOD_CHAIR")

static var DECOR_PK_CARVED_CHAIR: String:
	get: return TranslationServer.translate(&"DECOR_PK_CARVED_CHAIR")

static var DECOR_PK_WHITE_SOFA: String:
	get: return TranslationServer.translate(&"DECOR_PK_WHITE_SOFA")

static var DECOR_PK_NIGHTSTAND: String:
	get: return TranslationServer.translate(&"DECOR_PK_NIGHTSTAND")

static var DECOR_PK_BONSAI: String:
	get: return TranslationServer.translate(&"DECOR_PK_BONSAI")

static var DECOR_PK_RUG: String:
	get: return TranslationServer.translate(&"DECOR_PK_RUG")

static var DECOR_PK_COAT_STAND: String:
	get: return TranslationServer.translate(&"DECOR_PK_COAT_STAND")

static var DECOR_PK_LANDSCAPE: String:
	get: return TranslationServer.translate(&"DECOR_PK_LANDSCAPE")

static var DECOR_PK_PORTRAIT: String:
	get: return TranslationServer.translate(&"DECOR_PK_PORTRAIT")

static var DECOR_PK_GRANDFATHER_CLOCK: String:
	get: return TranslationServer.translate(&"DECOR_PK_GRANDFATHER_CLOCK")

static var DECOR_PK_GLOBE: String:
	get: return TranslationServer.translate(&"DECOR_PK_GLOBE")

static var DECOR_PK_SCULPTURE: String:
	get: return TranslationServer.translate(&"DECOR_PK_SCULPTURE")

static var DECOR_PK_BLUE_RUG: String:
	get: return TranslationServer.translate(&"DECOR_PK_BLUE_RUG")

static var DECOR_PK_FRIDGE: String:
	get: return TranslationServer.translate(&"DECOR_PK_FRIDGE")

static var DECOR_PK_SIDE_DESK: String:
	get: return TranslationServer.translate(&"DECOR_PK_SIDE_DESK")

static var DECOR_PK_SINK: String:
	get: return TranslationServer.translate(&"DECOR_PK_SINK")

static var DECOR_PK_DINER_TABLE: String:
	get: return TranslationServer.translate(&"DECOR_PK_DINER_TABLE")

static var DECOR_PK_FLOWER_VASE: String:
	get: return TranslationServer.translate(&"DECOR_PK_FLOWER_VASE")

static var DECOR_PK_FLOWER_POT: String:
	get: return TranslationServer.translate(&"DECOR_PK_FLOWER_POT")

static var DECOR_PK_CAR_PICTURE: String:
	get: return TranslationServer.translate(&"DECOR_PK_CAR_PICTURE")

static var DECOR_PK_DOTTED_RUG: String:
	get: return TranslationServer.translate(&"DECOR_PK_DOTTED_RUG")

static var DECOR_PK_ALOE: String:
	get: return TranslationServer.translate(&"DECOR_PK_ALOE")

static var DECOR_PK_CACTUS: String:
	get: return TranslationServer.translate(&"DECOR_PK_CACTUS")

static var DECOR_PK_DINER_SEAT: String:
	get: return TranslationServer.translate(&"DECOR_PK_DINER_SEAT")

static var DECOR_PK_GLASS_TABLE: String:
	get: return TranslationServer.translate(&"DECOR_PK_GLASS_TABLE")

static var DECOR_PK_SMALL_TABLE: String:
	get: return TranslationServer.translate(&"DECOR_PK_SMALL_TABLE")

static var DECOR_PK_PLANT: String:
	get: return TranslationServer.translate(&"DECOR_PK_PLANT")

static var DECOR_PK_SPROUT_POT: String:
	get: return TranslationServer.translate(&"DECOR_PK_SPROUT_POT")

static var DECOR_PK_POTTED_TREE: String:
	get: return TranslationServer.translate(&"DECOR_PK_POTTED_TREE")

static var DECOR_PK_TABLE_LAMP: String:
	get: return TranslationServer.translate(&"DECOR_PK_TABLE_LAMP")

static var CAMERA_TIP: String:
	get: return TranslationServer.translate(&"CAMERA_TIP")

static var DECOR_PK_ROSE_VASE: String:
	get: return TranslationServer.translate(&"DECOR_PK_ROSE_VASE")

static var DECOR_PK_LEAFY_POT: String:
	get: return TranslationServer.translate(&"DECOR_PK_LEAFY_POT")

static var DECOR_PK_FLOOR_LAMP: String:
	get: return TranslationServer.translate(&"DECOR_PK_FLOOR_LAMP")

static var DECOR_PK_DRINKS_CART: String:
	get: return TranslationServer.translate(&"DECOR_PK_DRINKS_CART")

static var DECOR_PK_STRIPED_RUG: String:
	get: return TranslationServer.translate(&"DECOR_PK_STRIPED_RUG")

static var DECOR_PK_OVAL_RUG: String:
	get: return TranslationServer.translate(&"DECOR_PK_OVAL_RUG")

static var DECOR_PK_RUNNER_RUG: String:
	get: return TranslationServer.translate(&"DECOR_PK_RUNNER_RUG")

static var DECOR_PK_DECORATED_TABLE: String:
	get: return TranslationServer.translate(&"DECOR_PK_DECORATED_TABLE")

static var PAD_LOST_HEAD: String:
	get: return TranslationServer.translate(&"PAD_LOST_HEAD")

static var PAD_LOST_TEXT: String:
	get: return TranslationServer.translate(&"PAD_LOST_TEXT")

static var TORNADO_FIRST: String:
	get: return TranslationServer.translate(&"TORNADO_FIRST")

static var CUE_LUCKY: String:
	get: return TranslationServer.translate(&"CUE_LUCKY")

static var CUE_DOUBLE: String:
	get: return TranslationServer.translate(&"CUE_DOUBLE")

static var CUE_PIGEON: String:
	get: return TranslationServer.translate(&"CUE_PIGEON")

static var CUE_FERRY: String:
	get: return TranslationServer.translate(&"CUE_FERRY")

static var CUE_METER: String:
	get: return TranslationServer.translate(&"CUE_METER")
